FORMAT: 1A
HOST: https://api.leadsift.com/1/

# LeadSift API

## Overview
The **LeadSift** platform uses advanced natural language processing techniques to detect demographic and consumer data about social 
media users.  This document describes the **LeadSift API**, a REST-based service that delivers these insights using standard HTTP 
semantics via resource-oriented URLs.  We use built-in HTTP features, including HTTP authentication and HTTP verbs, which are
easily handled using common client libraries across a range of programming languages.

## Authentication
The **LeadSift API** currently supports _Token-based_ authentication.  This method requires that clients supply an authentication
token, which must be supplied using the _Authorization_ header.  **Authentication is required for all API requests.**

In addition, **all requests must be made over HTTPS**.  Calls made over plain HTTP will fail.

## Request/Response Flows
There are two modes for developers to be aware of - **standard** and **webhook**.

### Standard
This is the flow that occurs when the **webhook_url** parameter is _not_ provided.  In this scenario, the user will receive one of
three possible non-error status codes and corresponding payloads:

* **200 OK** : The user was found in our data store, and is returned in the response payload as JSON.
* **202 Accepted** : The user was _not_ found in our data store.  In this instance, we accept the user for processing - the client should
            attempt to fetch the user again later.
* **404 Not Found** : The user has requested previously, but was found to be invalid (doesn't exist, marked as private, etc.).  New requests for
            that user should be made 24 hours later.

### Webhook
When the **webhook_url** is provided, one non-error status code is returned:

* **202 Accepted** : The user is accepted for processing.

This mode will trigger an HTTP POST of the result payload to a callback url specified by **webhook_url**.  Any response code other than 200 will indicate to our system
that the request was not successful, and it will retry the webhook about 10 seconds later.  The wait period doubles with each subsequent attempt.  If the url cannot be reached successfully after 3 attempts, the request will be dropped.  For development and testing purposes, we recommend using a service like [Requestb.in](http://requestb.in/) to create a temporary callback url.

## Errors
Conventional HTTP response codes are used to indicate success or failure of an API request. In general, codes in the 2xx range
indicate success, codes in the 4xx range indicate an error that resulted from the provided information (e.g. a required parameter
was missing), and codes in the 5xx range indicate an error with LeadSift's servers.

#### HTTP Status code summary
* **200 OK** : A user has been found and is returned in the response body.
* **202 Accepted** : The user has been accepted for processing.
* **400 Bad Request** : Often missing a required parameter.
* **401 Unauthorized** : No valid API key provided.
* **402 Request Failed** : Parameters were valid but request failed.
* **403 Forbidden** : The user is not permitted to perform the requested action.
* **404 Not Found** : The requested item doesn't exist.
* **500, 502, 503, 504** : Server errors - something went wrong on our end.

#### Error Payloads
When a **webhook_url** is provided, an error condition arising during processing will result in an 
error document being POST'ed to the callback url.  For example, a _user not found_ error could send a
document like this to your callback url, given a **user_id** of _123456789_:

    {
        "status": 404,
        "info": {
            "message": "'123456789' not found - try again in 24 hours",
            "type": "not_found",
            "param": "user_id"
        }
    }


#### Error types
* **not_found** : User not found
* **private_account** : User profile marked as private
* **server_error** : Internal server error
* **missing_parameter** : A required parameter is missing
* **invalid_parameter** : An invalid parameter was supplied


# Group Insights
These endpoints deliver demographic and consumer data for users of various social media networks.

## Twitter User Insights [/insights/twitter/{?user_id,username,webhook_url,webhook_id}]
### Fetch consumer insights for a Twitter user [GET]
Note that one of **user_id** or **username** is required, though supplying **user_id** is recommended whenever possible.  Twitter screen names may be changed at any time,
which makes them somewhat less reliable than user ids.

+ Parameters
    + user_id (optional, string, `515978659`) ... Twitter user id to be processed.
    + username (optional, string, `johndoe`) ... Twitter screen name to be processed.
    + webhook_url (optional, string, `http%3A%2F%2Fwww.example.com%2Fwebhook%2F`) ... Webhook URL - if provided, the result will be sent via HTTP POST to the url.  Must be URL-encoded.
    + webhook_id (optional, string, `abc123`) ... Identifier sent along with result to the webhook url.  Must be URL-encoded
+ Request
    + Headers
    
                Authorization: Token yourtoken

+ Response 200 (application/json)
    + Body

            {
              "status": 200,
              "info": {
                "message": "ok"
              },
              "data": {
                "leadsift": {
                  "brand_mentions": [],
                  "features": {
                    "is_corporate": false,
                    "interests": [
                      {
                        "text": "politics"
                      },
                      {
                        "text": "science"
                      },
                      {
                        "text": "technology"
                      },
                      {
                        "text": "business"
                      },
                      {
                        "text": "automobiles"
                      }
                    ],
                    "lifestyle": [],
                    "active_time": "AFTERNOON",
                    "gender": "unknown",
                    "age": "unknown",
                    "has_car": false,
                    "is_adult": true,
                    "devices": {
                      "desktop": {
                        "stats": {
                          "count": 1
                        }
                      }
                    },
                    "life_events": [],
                    "has_house": false,
                    "is_influencer": true,
                    "brands": [
                      {
                        "category": "other",
                        "id": "twitter"
                      },
                      {
                        "category": "products",
                        "id": "volkswagen"
                      },
                      {
                        "category": "websites",
                        "id": "mashable"
                      }
                    ],
                    "is_teenager": false,
                    "professions": [],
                    "has_pet": false
                  }
                },
                "data": {
                  "author": {
                    "username": "leadsift",
                    "bio": "Social Media Lead Generation & Identification Platform. An easy to use software that enables businesses to find and engage with relevant leads on Social Media.",
                    "stats": {
                      "friends": 362,
                      "followers": 958,
                      "statuses": 1344
                    },
                    "name": "LeadSift",
                    "link": "https://twitter.com/leadsift",
                    "location": {
                      "text": "Halifax, Nova Scotia",
                      "details": {
                        "city": "Halifax",
                        "geonameid": "6324729",
                        "country": "Canada",
                        "state": "Nova Scotia",
                        "country_code": "CA",
                        "state_code": "NS",
                        "type": "city"
                      }
                    },
                    "id": "515978659",
                    "avatar": {
                      "https": "https://pbs.twimg.com/profile_images/378800000186360874/bafa400a1cc0273f0ef6c3753cb7abba.jpeg"
                    }
                  }
                }
              },
              "request_id": "00000000-0000-0000-0000-000000000000"
            }

## Instagram User Insights [/insights/instagram/{?webhook_url,webhook_id}]
### Deliver consumer insights for a Instagram user [POST]
This endpoint requires clients to supply a webhook URL for results to be POST'ed to. The request should be sent with a JSON document payload containing data for the Instagram user to be processed.  The document supplied should adhere to the JSON request schema.
#### Input JSON Schema

    {
      "required": true,
      "properties": {
        "posts": {
          "items": {
            "type": "object",
            "properties": {
              "text": {
                "required": true,
                "type": "string",
                "description": "Post content"
              },
              "created_at": {
                "required": true,
                "type": "number",
                "description": "Post's creation time as a UNIX timestamp"
              },
              "id": {
                "required": true,
                "minLength": 1,
                "type": "string",
                "description": "ID for this post, if provided by the social network"
              }
            }
          },
          "additionalItems": false,
          "required": true,
          "type": "array",
          "description": "Posts for this social media user"
        },
        "user": {
          "required": true,
          "type": "object",
          "description": "User information",
          "properties": {
            "username": {
              "minLength": 1,
              "required": true,
              "type": "string",
              "description": "Screen name for the user"
            },
            "bio": {
              "required": false,
              "type": "string",
              "description": "User description, if provided"
            },
            "name": {
              "minLength": 1,
              "required": true,
              "type": "string",
              "description": "User's real name"
            },
            "created_at": {
              "required": false,
              "type": "number",
              "description": "User's creation time as a UNIX timestamp"
            },
            "website": {
              "required": false,
              "type": "string",
              "description": "User's website"
            },
            "avatar": {
              "required": false,
              "type": "string",
              "description": "User profile image"
            },
            "id": {
              "minLength": 1,
              "required": true,
              "type": "string",
              "description": "User ID supplied by social media network"
            }
          }
        }
      },
      "additionalProperties": false,
      "$schema": "http: //json-schema.org/draft-03/schema",
      "type": "object",
      "id": "#"
    }

+ Parameters
    + webhook_url (required, string, `http%3A%2F%2Fwww.example.com%2Fwebhook%2F`) ... Webhook URL - the result will be sent via HTTP POST to the url.  Must be URL-encoded.
    + webhook_id (optional, string, `abc123`) ... Identifier sent along with result to the webhook url.  Must be URL-encoded
+ Request
    + Headers
    
                Authorization: Token yourtoken
                Content-Type:  application/json

    + Body

                {
                    "user": {
                        "id": "123456789",
                        "username": "johndoe",
                        "name": "John Doe",
                        "bio": "Biography of John Doe",
                        "created_at": 123456789
                        "website": "http://www.example.com",
                    },
                    "posts": [
                        { "id": "1", "text": "Hello World", "created_at": 1212121212 },
                        { "id": "2", "text": "Testing, Testing, 1, 2, 3", "created_at": 123456789 }
                    ]
                }

    + Schema

                {
                  "required": true,
                  "properties": {
                    "posts": {
                      "items": {
                        "type": "object",
                        "properties": {
                          "text": {
                            "required": true,
                            "type": "string",
                            "description": "Post content"
                          },
                          "created_at": {
                            "required": true,
                            "type": "number",
                            "description": "Post's creation time as a UNIX timestamp"
                          },
                          "id": {
                            "required": true,
                            "minLength": 1,
                            "type": "string",
                            "description": "ID for this post, if provided by the social network"
                          }
                        }
                      },
                      "additionalItems": false,
                      "required": true,
                      "type": "array",
                      "description": "Posts for this social media user"
                    },
                    "user": {
                      "required": true,
                      "type": "object",
                      "description": "User information",
                      "properties": {
                        "username": {
                          "minLength": 1,
                          "required": true,
                          "type": "string",
                          "description": "Screen name for the user"
                        },
                        "bio": {
                          "required": false,
                          "type": "string",
                          "description": "User description, if provided"
                        },
                        "name": {
                          "minLength": 1,
                          "required": true,
                          "type": "string",
                          "description": "User's real name"
                        },
                        "created_at": {
                          "required": false,
                          "type": "number",
                          "description": "User's creation time as a UNIX timestamp"
                        },
                        "website": {
                          "required": false,
                          "type": "string",
                          "description": "User's website"
                        },
                        "avatar": {
                          "required": false,
                          "type": "string",
                          "description": "User profile image"
                        },
                        "id": {
                          "minLength": 1,
                          "required": true,
                          "type": "string",
                          "description": "User ID supplied by social media network"
                        }
                      }
                    }
                  },
                  "additionalProperties": false,
                  "$schema": "http: //json-schema.org/draft-03/schema",
                  "type": "object",
                  "id": "#"
                }


+ Response 202 (application/json)
    + Body
    
## Batch Requests [/batch/]
### Run several requests in a batch [POST]
The Batch Requests endpoint allows you to batch several API requests into a single request.  This endpoint will proxy up to 20 requests per batch for any
other endpoint that accepts GET requests.  Any invalid endpoints (incorrect hostname, invalid endpoint, etc.) will be ignored.

+ Request
    + Headers
    
                Authorization: Token yourtoken
                Content-Type:  application/json

    + Body

                {
                    "requests": [
                        "https://api.leadsift.com/1/insights/twitter/?username=leadsift",
                        "https://api.leadsift.com/1/insights/twitter/?username=twitter"
                    ]
                }

+ Response 200 (application/json)
    + Body
    
                {u'data': {u'responses': [{u'data': {u'data': {u'author': {u'avatar': {u'http': u'http://pbs.twimg.com/profile_images/378800000186360874/bafa400a1cc0273f0ef6c3753cb7abba_normal.jpeg',
                        u'https': u'https://pbs.twimg.com/profile_images/378800000186360874/bafa400a1cc0273f0ef6c3753cb7abba_normal.jpeg'},
                       u'bio': u'Helping Brands Identify, Understand and Reach Consumers from Social Media.',
                       u'contributors': False,
                       u'created_at': u'2012-03-05T23:34:31',
                       u'id': u'515978659',
                       u'language': u'en',
                       u'link': u'https://twitter.com/leadsift',
                       u'location': {u'details': {u'city': u'Halifax',
                         u'continent_code': u'NA',
                         u'country': u'Canada',
                         u'country_code': u'CA',
                         u'geonameid': u'6324729',
                         u'population': 359111,
                         u'score': 121,
                         u'state': u'Nova Scotia',
                         u'state_code': u'NS',
                         u'type': u'city'},
                        u'text': u'Halifax, Nova Scotia'},
                       u'name': u'LeadSift',
                       u'stats': {u'favorites': 0,
                        u'followers': 1059,
                        u'friends': 408,
                        u'listed_count': 61,
                        u'statuses': 1415},
                       u'status': u'active',
                       u'timezone': {u'name': u'Atlantic Time (Canada)',
                        u'utc_offset': -14400},
                       u'urls': [],
                       u'username': u'leadsift',
                       u'verified': False,
                       u'website': u'http://www.leadsift.com'}},
                     u'leadsift': {u'features': {u'active_time': u'MORNING',
                       u'age': u'50+',
                       u'brands': [{u'category': u'other', u'id': u'twitter'},
                        {u'category': u'websites', u'id': u'bleacher_report'}],
                       u'devices': {u'desktop': {u'stats': {u'count': 1, u'ratio': 1.0}}},
                       u'gender': u'unknown',
                       u'has_car': False,
                       u'has_family': False,
                       u'has_house': False,
                       u'has_job': False,
                       u'has_kid': False,
                       u'has_pet': False,
                       u'interests': [{u'text': u'science'},
                        {u'text': u'travel'},
                        {u'text': u'music'},
                        {u'text': u'business'},
                        {u'text': u'politics'}],
                       u'is_corporate': True,
                       u'is_influencer': True,
                       u'is_married': False,
                       u'is_personal': False,
                       u'is_teenager': False,
                       u'life_events': [],
                       u'lifestyle': [{u'text': u'excitable'}, {u'text': u'hni'}],
                       u'professions': []}}},
                    u'info': {u'message': u'ok'},
                    u'request_id': u'78e7bf42-352f-46b7-9ba8-ea82b883ff0f',
                    u'status': 200},
                   {u'data': {u'data': {u'author': {u'avatar': {u'http': u'http://pbs.twimg.com/profile_images/530553072594874368/7f9QErOD_normal.png',
                        u'https': u'https://pbs.twimg.com/profile_images/530553072594874368/7f9QErOD_normal.png'},
                       u'bio': u'Your official source for news, updates and tips from Twitter, Inc.',
                       u'contributors': False,
                       u'created_at': u'2007-02-20T14:35:54',
                       u'id': u'783214',
                       u'language': u'en',
                       u'link': u'https://twitter.com/twitter',
                       u'location': {u'details': {u'city': u'San Francisco',
                         u'continent_code': u'NA',
                         u'country': u'United States',
                         u'country_code': u'US',
                         u'geonameid': u'5391959',
                         u'population': 805235,
                         u'score': 211,
                         u'state': u'California',
                         u'state_code': u'CA',
                         u'type': u'city'},
                        u'text': u'San Francisco, CA'},
                       u'name': u'Twitter',
                       u'stats': {u'favorites': 0,
                        u'followers': 33790197,
                        u'friends': 101,
                        u'listed_count': 86778,
                        u'statuses': 1852},
                       u'status': u'active',
                       u'timezone': {u'name': u'Pacific Time (US & Canada)',
                        u'utc_offset': -28800},
                       u'urls': [],
                       u'username': u'twitter',
                       u'verified': True,
                       u'website': u'http://blog.twitter.com/'}},
                     u'leadsift': {u'features': {u'active_time': u'MORNING',
                       u'age': u'50+',
                       u'brands': [{u'category': u'clothing', u'id': u'mattingly_sports'},
                        {u'category': u'other', u'id': u'cnet'},
                        {u'category': u'other', u'id': u'nbcuniversal'},
                        {u'category': u'other', u'id': u'twitter'},
                        {u'category': u'retail', u'id': u'amazon'},
                        {u'category': u'services', u'id': u'comcast'},
                        {u'category': u'websites', u'id': u'ars_technica'},
                        {u'category': u'websites', u'id': u'engadget'},
                        {u'category': u'websites', u'id': u'gizmodo'},
                        {u'category': u'websites', u'id': u'nytimes'},
                        {u'category': u'websites', u'id': u'readwrite'},
                        {u'category': u'websites', u'id': u'techcrunch'},
                        {u'category': u'websites', u'id': u'the_real_news'},
                        {u'category': u'tvshows', u'id': u'the_ellen_degeneres_show'},
                        {u'category': u'tvshows', u'id': u'jeopardy'},
                        {u'category': u'tvshows', u'id': u'good_morning_america'}],
                       u'devices': {u'desktop': {u'stats': {u'count': 2,
                          u'ratio': 0.6666666666666666}},
                        u'mobile': {u'stats': {u'count': 1, u'ratio': 0.3333333333333333}}},
                       u'gender': u'unknown',
                       u'has_car': False,
                       u'has_family': False,
                       u'has_house': False,
                       u'has_job': False,
                       u'has_kid': False,
                       u'has_pet': False,
                       u'interests': [{u'text': u'politics'},
                        {u'text': u'beauty_fashion'},
                        {u'text': u'books'},
                        {u'text': u'technology'},
                        {u'text': u'business'}],
                       u'is_corporate': True,
                       u'is_influencer': True,
                       u'is_married': False,
                       u'is_personal': False,
                       u'is_teenager': False,
                       u'life_events': [],
                       u'lifestyle': [],
                       u'professions': []}}},
                    u'info': {u'message': u'ok'},
                    u'request_id': u'19aa3ac4-700d-47f2-9c27-04dafe844d4a',
                    u'status': 200}]},
                 u'info': {u'message': u'ok'},
                 u'request_id': u'b2947166-db49-4e72-95d6-f1ee92c9fa96',
                 u'status': 200}    

